name: deploy-container-juandiego

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY_SERVER_URL: jfernandezcr.azurecr.io
  IMAGE_NAME: jfernandez-dockerimg
  APP_SERVICE_NAME: jfernandez-appservice
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-B-DEV
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: jfernandez

jobs:
  build-infra:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3
      
      # Lint Bicep code
      - name: Run Bicep linter
        run: az bicep build --file ./main.bicep
      
      # Upload Bicep build artifact
      - name: Upload Bicep build artifact
        uses: actions/upload-artifact@v3
        with:
          name: bicep-build
          path: ./main.bicep

  deploy-infra:
    runs-on: ubuntu-latest
    needs: build-infra
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Download Bicep build artifact
      - name: Download Bicep build artifact
        uses: actions/download-artifact@v3
        with:
          name: bicep-build
      
      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy infrastructure using Bicep
      - name: Deploy
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./main.bicep
          parameters: ./parameters.bicepparam

  build-push-image:
    runs-on: ubuntu-latest
    needs: deploy-infra
    outputs:
      image-version: ${{ steps.image-version.outputs.version }}

    steps:
      - uses: actions/checkout@v3

      # Log into Azure
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Set image version
      - name: Set image version
        id: image-version
        run: |
          echo "version=$(date +'%Y.%m.%d.%H.%M')" >> $GITHUB_ENV

      # Print Docker images
      - name: Print images
        run: |
          echo "Images"
          docker images

      # Build and push Docker image
      - name: Docker build and push image
        env:
          DOCKER_REGISTRY_SERVER_URL: ${{ env.DOCKER_REGISTRY_SERVER_URL }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        run: |
          docker build -t ${{ env.DOCKER_REGISTRY_SERVER_URL }}/${{ env.IMAGE_NAME }}:${{ env.version }} .
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ env.DOCKER_REGISTRY_SERVER_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
          docker push ${{ env.DOCKER_REGISTRY_SERVER_URL }}/${{ env.IMAGE_NAME }}:${{ env.version }}

  deploy-container:
    runs-on: ubuntu-latest
    needs: build-push-image
    steps:
      # Log into Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Docker image to Azure Web App
      - name: Deploy Docker Image to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_SERVICE_NAME }}
          images: |
            ${{ env.DOCKER_REGISTRY_SERVER_URL }}/${{ env.IMAGE_NAME }}:${{ needs.build-push-image.outputs.image-version }}
